# Site wide configuration

title: Sayan Ghosal           
locale:           en_US
url: https://sayangsep.github.io
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Site owner
owner:
  name: Sayan Ghosal
  avatar: "sayan.jpg"
  position: Computational Scientist
  school: Broad Institute
  place: Cambridge, U.S.A
  bio: "Computational Scientist, Broad Institute"
  email: ghosal@broadinstitute.org
  disqus-shortname:
  twitter: #username
  facebook:  #username
  google:
    plus: 
    analytics: G-PYG3KL47EY
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: sayangsep
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: sayan-ghosal-40264618a #username
  googlescholar: "https://scholar.google.com/citations?user=uUsqt_4AAAAJ&hl=en"
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  scholar: 

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
